// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/authors-forge-variants/BrightAuthority.tsx": () => import("../components/mockups/authors-forge-variants/BrightAuthority.tsx"),
  "./components/mockups/authors-forge-variants/ElectricRebellion.tsx": () => import("../components/mockups/authors-forge-variants/ElectricRebellion.tsx")
};
